### ISSUE TITLE
运行SlowFast_features.py出现问题

### ISSUE THREAD

**Issue by 1105430565** [lixinustc/KVQ-Challenge-CVPR-NTIRE2024#1]
运行SlowFast_features.py时出现下述错误：
![image](https://github.com/lixinustc/KVQ-Challenge-CVPR-NTIRE2024/assets/82871602/b80f55cf-0a8e-447b-ae14-9aaac834ce85)

**Comment by yeppp27** [comment]
您好！slowfast_feature.py已更新，其中resize设成224可以解决这个问题  
祝好
